#!/bin/bash

# Use this bash script to autoconnect to the sql database from school computers
## once entered, type "connect sbingham" to connect to the schema
## from here you can view tables using SQL commands, such as "SELECT * FROM provider;"
echo 
echo =======================================================================================================
echo \>\> Logging on to ChocoAn MySQL Database
echo =======================================================================================================
echo \>\> Once you have connected to the MySQL DB below, type: \"connect sbingham\" to connect to our schema
echo =======================================================================================================
echo \>\> From here you can view tables using SQL commands, ie: \"SELECT \* FROM provider\;\"
echo =======================================================================================================
echo   
mysql -h db.cecs.pdx.edu -u sbingham -px6Tcbcs5*a
