#include "cadb.h"
#include <sys/time.h>

int
main()
{
	std::cout << "\n>> Start C++ connect mysql test example \n";
	cadb mydb;

	//struct timeval start_time;
	//gettimeofday(&start_time, NULL);
	//srand(start_time.tv_usec);
#ifdef TEST
	cout << "Define test worked!" << endl;
#endif // TEST
<<<<<<< HEAD
	mydb.setCell("provider", "provider_number", "333333333", "provider_status", "0");

	//cout << "Charlie status: " << charliestatus << endl;
=======
	int charliestatus = mydb.getStatus("member", 33);

	cout << "Charlie status: " << charliestatus << endl;
>>>>>>> 2cc0a9c138dfdf31f35c675a19bf9492fe40ee10

	//int provider_id = 0;//(rand() % 25) + 1;
	//int service_id = 0; //(rand() % 15) + 1;
	//int member_id = 0;//(rand() % 31) + 1;
	//int month = 11;//(rand() % 3) + 9;
	//int day = 0; //(rand() % 13) + 1;

	//string comments = "Autogenerated test comment from Sam Bingham";
	//string date = "2022-11-16";///"2022-";

	//int retval = mydb.getStatus("member", 34);
	//cout << "Retval = " << retval << endl;

	//int visits_per_day = (rand() % 15) + 15;
	
	/*for (int i = 0; i < visits_per_day; ++i){
		//date.clear();// = NULL;
		provider_id = (rand() % 25) + 1;
		service_id = (rand() % 16) + 1;
		member_id = (rand() % 31) + 1;
		//day = (rand() % 13) + 1;

		//date = "2022-";
		//date += to_string(month);
		//date += "-";
		//date += to_string(day);

		mydb.insertVisit(date, provider_id, service_id, member_id, comments);
	}*/
	

	

	
	
	return 0;
};
